parameters:
  environment: someenv
  applicationName: gridwich

steps:

- bash: |
    set -eu
    cat ./variables.json
    cat ./variables.json | jq -r '
      . as $in
      | keys[] 
      | ["##vso[task.setvariable variable=" + . + "]" + ($in[.] | tostring)]
      | @tsv'
  name: TerraformOutputs
  displayName: Export variables outputs
  workingDirectory: $(Pipeline.Workspace)/variables_${{ parameters.environment }}_top

- task: AzureCLI@2
  displayName: 'Turn on Storage Analytics for all Storage accounts'
  inputs:
    azureSubscription: ${{parameters.serviceConnection}}
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      set -eu
      storaccts=$(az storage account list --query [].name -o tsv)
      for acct in $storaccts
      {
        if [[  $acct =~ '${{ parameters.environment }}'$ ]]; then
          echo "Setting Storage Analytics for $acct"
          az storage logging update --log rwd --retention 365 --services b --account-name $acct 2> /dev/null
        else
          echo "Ignored Storage Analytics for $acct"
        fi
      }
    addSpnToEnvironment: true
