/*
* This file was generated by using: https://xmltocsharp.azurewebsites.net/
* To recreate it, find a representative ism file and paste it into the tool.
*/

using System.Collections.Generic;
using System.Xml.Serialization;

#pragma warning disable SA1600 // Elements should be documented - this is a representation of a standardized file type
#pragma warning disable CA2227 // Collection properties should be read only
namespace Gridwich.SagaParticipants.Publication.MediaServicesV3.Models
{
    [XmlRoot(ElementName = "smil", Namespace = "http://www.w3.org/2001/SMIL20/Language")]
    public class IsmFile
    {
        [XmlElement(ElementName = "head", Namespace = "http://www.w3.org/2001/SMIL20/Language")]
        public Head Head { get; set; }
        [XmlElement(ElementName = "body", Namespace = "http://www.w3.org/2001/SMIL20/Language")]
        public Body Body { get; set; }
        [XmlAttribute(AttributeName = "xmlns")]
        public string Xmlns { get; set; }
    }

    [XmlRoot(ElementName = "meta", Namespace = "http://www.w3.org/2001/SMIL20/Language")]
    public class Meta
    {
        [XmlAttribute(AttributeName = "name")]
        public string Name { get; set; }
        [XmlAttribute(AttributeName = "content")]
        public string Content { get; set; }
    }

    [XmlRoot(ElementName = "head", Namespace = "http://www.w3.org/2001/SMIL20/Language")]
    public class Head
    {
        [XmlElement(ElementName = "meta", Namespace = "http://www.w3.org/2001/SMIL20/Language")]
        public List<Meta> Meta { get; set; }
    }

    [XmlRoot(ElementName = "param", Namespace = "http://www.w3.org/2001/SMIL20/Language")]
    public class Param
    {
        [XmlAttribute(AttributeName = "name")]
        public string Name { get; set; }
        [XmlAttribute(AttributeName = "value")]
        public string Value { get; set; }
        [XmlAttribute(AttributeName = "valuetype")]
        public string Valuetype { get; set; }
    }

    [XmlRoot(ElementName = "audio", Namespace = "http://www.w3.org/2001/SMIL20/Language")]
    public class Audio
    {
        [XmlElement(ElementName = "param", Namespace = "http://www.w3.org/2001/SMIL20/Language")]
        public List<Param> Param { get; set; }
        [XmlAttribute(AttributeName = "src")]
        public string Src { get; set; }
        [XmlAttribute(AttributeName = "systemBitrate")]
        public string SystemBitrate { get; set; }
        [XmlAttribute(AttributeName = "systemLanguage")]
        public string SystemLanguage { get; set; }
    }

    [XmlRoot(ElementName = "video", Namespace = "http://www.w3.org/2001/SMIL20/Language")]
    public class Video
    {
        [XmlElement(ElementName = "param", Namespace = "http://www.w3.org/2001/SMIL20/Language")]
        public List<Param> Param { get; set; }
        [XmlAttribute(AttributeName = "src")]
        public string Src { get; set; }
        [XmlAttribute(AttributeName = "systemBitrate")]
        public string SystemBitrate { get; set; }
    }

    [XmlRoot(ElementName = "switch", Namespace = "http://www.w3.org/2001/SMIL20/Language")]
    public class Switch
    {
        [XmlElement(ElementName = "audio", Namespace = "http://www.w3.org/2001/SMIL20/Language")]
        public List<Audio> Audio { get; set; }
        [XmlElement(ElementName = "video", Namespace = "http://www.w3.org/2001/SMIL20/Language")]
        public List<Video> Video { get; set; }
    }

    [XmlRoot(ElementName = "body", Namespace = "http://www.w3.org/2001/SMIL20/Language")]
    public class Body
    {
        [XmlElement(ElementName = "switch", Namespace = "http://www.w3.org/2001/SMIL20/Language")]
        public Switch Switch { get; set; }
    }
}
#pragma warning restore CA2227 // Collection properties should be read only
#pragma warning restore SA1600 // Elements should be documented
